Update utils.py: make datetime object UTC timezone aware.
datetime.utcnow() is deprecated in py 3.12+ and it is recommended to use datetime.now(UTC)

it creates a timezone aware object and pyrogram's previous datetime object was timezone naive which resulted in:

TypeError: can't subtract offset-naive and offset-aware datetimes.